worker_processes auto;
pid /tmp/nginx.pid;
error_log /dev/stderr warn;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format privacy '$remote_addr [$time_local] "$request_method $uri $server_protocol" '
                       '$status $body_bytes_sent rt=$request_time ua="$http_user_agent"';
    access_log /dev/stdout privacy;
    sendfile on;
    keepalive_timeout 65;
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path /tmp/proxy_temp;
    fastcgi_temp_path /tmp/fastcgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;
    scgi_temp_path /tmp/scgi_temp;

    gzip on;
    gzip_types application/javascript application/json image/svg+xml text/css text/plain;

    include /etc/nginx/conf.d/*.conf;
}
